export interface SearchResponse {
  headers: Headers;
  data: Data;
  status: number;
}

export interface Data {
  r01: string;
  r02: string;
  r03: string;
  r04: string;
  r05: any[];
  r06: R06[];
}

export interface R06 {
  r01: string;
  r02: number;
  r03: number;
  r04: number;
  r05: number;
  r06: number;
  r07: number;
  r08: number;
  r09: number;
  r10: number;
  r11: number;
  r12: number;
  r13: number;
  r14: number;
  r15: string;
  r16: string;
  r17: string;
  r18: number;
  r19: null;
  r20: string;
  r21: number;
  r22: null;
  r23: null;
  r24: string;
  r25: string;
  r26: string;
  r27: string;
  r28: string;
  r29: null;
  r30: R30;
  r31: string;
}

export enum R30 {
  Empty = '\u00ad$',
}

export interface Headers {
  'cache-control': string;
  pragma: string;
  'content-type': string;
  expires: string;
  vary: string;
  server: string;
  'strict-transport-security': string;
  'x-aspnet-version': string;
  'set-cookie': string[];
  p3p: string;
  'content-security-policy': string;
  date: string;
  connection: string;
  'content-length': string;
}

// Generated by https://quicktype.io

export interface CourseDB {
  CourseID: number;
  RegionName: RegionName;
  AreaName: AreaName;
  CourseName: string;
  CityName: string;
  CityID: number;
  CountryName: CountryName;
}

export type AreaName = 'Newark' | 'Northern New Jersey';

export type CountryName = 'United States';

export type RegionName = 'New Jersey';

export enum R16 {
  DarlingtonGolfCourse = 'Darlington Golf Course',
  OrchardHillsGolfCourse = 'Orchard Hills Golf Course',
  OverpeckGolfCourse = 'Overpeck Golf Course',
  RockleighGolfCourseBlue = 'Rockleigh Golf Course - Blue',
  RockleighGolfCourseRedWhite = 'Rockleigh Golf Course - Red/White',
  SoldierHillGolfCourse = 'Soldier Hill Golf Course',
  ValleyBrookGolfCourse = 'Valley Brook Golf Course',
}

export interface SearchRequest {
  p01: number[]; // courses
  p02: string; // date format(MM/DD/YYY)
  p03: string; // start time formaat("H:MM S")
  p04: string; // end time formaat("H:MM S")
  p05: number; // min players 0
  p06: number; // max players up to 4
  p07: boolean; //false
}

export interface SearchForm {
  userId: string;
  courses: number[]; // courses
  date: string; // date format(MM/DD/YYY)
  startTime: string; // start time formaat("H:MM S")
  endTime: string; // end time formaat("H:MM S")
  min: number; // min players 0
  max: number; // max players up to 4
}
