import axios from 'axios';
import { updateTicketSearchFailed } from '../models/tickets';

export const teeTimeConflict = async (
  body: TeeTimeConflictRequest,
  cookies: string,
  id: number
) => {
  try {
    const promise = await axios({
      headers: {
        Cookie: cookies,
      },

      method: 'post',
      url: 'https://bergencountyrba.ezlinksgolf.com/api/cart/checkteetimeconflicts',
      data: body,
    });
    return promise;
  } catch (err) {
    updateTicketSearchFailed(id, err, 'holdReservation Request');
  }
};

// Generated by https://quicktype.io

export interface TeeTimeConflictRequest {
  CourseID: string;
  ContactID: string;
  SponsorID: string;
  TeeTime: string;
}

export const createTeeTimeConflictObj = (cart: any, loggedIn: any) => {
  return {
    SponsorID: `${cart.SponsorID}`, // getAllItems response cart[0].SponsorID to string
    ContactID: `${loggedIn.ContactID}`, // loggedIn?.data.ContactID,
    TeeTime: cart.TeeTime,
    CourseID: `${cart.CourseID}`,
  };
};
